Add websocket reconnect
triniti/cms-js pull request #255
Opened 2020-10-01 03:57 UTC by tbone1020

2020-10-01 18:11 UTC, efjacobson commented
note: we need to get final sign off from Sam on the wording used here

2020-10-02 19:16 UTC, efjacobson commented
@tbone1020 @arunkarnati final wording is this:

> Your active edits connection is unstable; we have attempted to reconnect but it is beyond repair. Other users may not be able to see your activity. Please save any pending work and refresh the page. If this problem persists you may want to alert team members of your activity. Thank you.

with this change, there is no longer a need to attempt to reconnect

2020-10-05 17:23 UTC, arunkarnati requested changes
@tbone1020 - according to Eric's comment here, https://github.com/triniti/cms-js/pull/255#issuecomment-702912409, we don't need to make any additional attempts to reconnect. Please remove the wants-to-reconnect code and display an alert message with the wording quoted in the above comment.

2020-10-05 17:23 UTC, arunkarnati commented on CHANGELOG.md
> +* issue #1225: Look For Solutions To Reconnect CMS Web Socket When It Disconnects.
@tbone1020 - please use an issue number if it is referring to a ticket created in this repo. e.g., https://github.com/triniti/cms-js/issues/232

2020-10-09 21:03 UTC, arunkarnati commented
> @tbone1020 - according to Eric's comment here, [#255 (comment)](https://github.com/triniti/cms-js/pull/255#issuecomment-702912409), we don't need to make any additional attempts to reconnect. Please remove the wants-to-reconnect code and display an alert message with the wording quoted in the above comment.

@tbone1020 - checking in to see if you had a chance to look at my feedback and have any questions?

2020-10-09 21:22 UTC, efjacobson commented
@arunkarnati @tbone1020 they are actually still waiting on final language here, lets park this until that is settled

2020-10-09 21:23 UTC, arunkarnati commented
> @arunkarnati @tbone1020 they are actually still waiting on final language here, lets park this until that is settled

10-4

2020-11-11 00:04 UTC, efjacobson requested changes

2020-11-11 00:04 UTC, efjacobson commented on src/plugins/raven/sagas/connectionFlow.js
> +      if (userWantsToReconnect.value && userWantsToReconnect.value === true) {
@tbone1020 you can remove all this reconnect stuff since they dont want it anymore - it's just a notification now

2020-11-11 02:31 UTC, efjacobson commented on src/plugins/raven/sagas/connectionFlow.js
> -      const userWantsToReconnect = yield swal.fire({
@tbone1020 you do still want to fire the swal, you just dont need to do anything else

2020-11-11 17:23 UTC, efjacobson commented on src/plugins/raven/sagas/connectionFlow.js
>    for (let i = 0; i < maxConnectionAttempts; i += 1) {
@tbone1020 you can just hardcode this this to 5 like it was before since we wont be changing it

2020-11-11 17:23 UTC, tbone1020 commented
@efjacobson I added sweet alert back.

2020-11-11 17:31 UTC, efjacobson commented
@tbone1020 also, it looks like the `warning` type is the closest to the mock https://sweetalert2.github.io/#icons

2020-11-11 17:47 UTC, tbone1020 commented
@efjacobson hard coded maxConnectionAttemps, changed alert to "warning", and removed "yield" from in front of the sweet alert since we're not waiting for users response.

2020-11-11 17:52 UTC, efjacobson commented on src/plugins/raven/sagas/connectionFlow.js
> +  let attempts = 10;
@tbone1020 leave this at 0 where it was, otherwise it will only attempt a single time

2020-11-11 17:57 UTC, tbone1020 commented
@efjacobson changed it to 10 for testing purposes. It has been changed back to 0.

2020-11-11 18:28 UTC, efjacobson approved these changes

2020-11-11 18:50 UTC, merged