Title warning in red
triniti/cms-js pull request #282
Opened 2021-01-12 22:21 UTC by bhsiao55

Set red error message when article title length is at 75 characters or greater.

2021-01-19 23:16 UTC, arunkarnati requested changes

2021-01-19 23:16 UTC, arunkarnati commented on src/plugins/news/services/ArticleSubscriber.js
> +      formEvent.addError('title', `recommendation: keep title less than ${TITLE_LENGTH_LIMIT} characters to avoid title extending too long in search results. (${title.length}/${TITLE_LENGTH_LIMIT})`)
@bhsiao55 - this is a form validation error, and it prevents the form submission, which is not the desired behavior. Please move this logic to `onWarnForm`

2021-01-19 23:16 UTC, arunkarnati commented on src/plugins/news/services/ArticleSubscriber.js
> +          redux.dispatch(touch(formNames.ARTICLE, 'title'));
@bhsiao55 - once you address the above change, I know this can be removed, but I'm curious why marking the title field `touched` is needed here?

2021-01-21 05:00 UTC, bhsiao55 commented
@arunkarnati added red messaging tp story field as well

2021-01-21 19:49 UTC, arunkarnati approved these changes

2021-01-21 20:26 UTC, merged