create alert for node load timeouts
triniti/cms-js pull request #292
Opened 2021-02-18 20:10 UTC by aloncohenn

2021-02-18 23:18 UTC, efjacobson requested changes
@aloncohenn see if Sam wants the swal button to refresh, like how the stale data has one that does that

2021-02-19 00:24 UTC, aloncohenn commented on src/plugins/ncr/screens/node/index.jsx
> +          swal.fire({
made some other updates as well

2021-02-19 01:26 UTC, efjacobson commented on src/plugins/ncr/screens/node/index.jsx
> +          const nodeLabel = nodeRef.getLabel().charAt(0).toUpperCase() + nodeRef.getLabel().slice(1);
@aloncohenn this is gonna break down when you have something that is hyphenated, not worth it, just use the raw label

2021-02-22 20:24 UTC, efjacobson approved these changes

2021-02-22 20:24 UTC, efjacobson approved these changes

2021-02-22 20:26 UTC, merged